name: Build and deploy actions image to AWS ECR and to demo ECS

# Only build on merge/push to main
on:
  push:
    branches:
    - main
    tags:
    - '*'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: actions-private
  ECR_REPOSITORY_TESTBOT: demo-actions-testbot
  ECR_REPOSITORY_PALMU: demo-actions-palmu
  RASA_SDK_IMAGE: rasa/rasa-sdk:2.8.3
  # The commit SHA that triggered the workflow run
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/automation-oidc-github
        role-session-name: actions-build-and-deploy
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.production --build-arg RASA_SDK_IMAGE=$RASA_SDK_IMAGE .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_TESTBOT:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_TESTBOT:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_PALMU:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_PALMU:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "::set-output name=imagetestbot::$ECR_REGISTRY/$ECR_REPOSITORY_TESTBOT:$IMAGE_TAG"
        echo "::set-output name=imagepalmu::$ECR_REGISTRY/$ECR_REPOSITORY_PALMU:$IMAGE_TAG"

    - name: Tag ECR image with latest as well
      run: |
        MANIFEST=$(aws ecr batch-get-image --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG --output json | jq --raw-output --join-output '.images[0].imageManifest')
        aws ecr put-image --repository-name $ECR_REPOSITORY --image-tag latest --image-manifest "$MANIFEST"
    
    - name: Fill systems manager parameter with latest version id
      run: aws ssm put-parameter --name actions-image-tag-latest --type String --value $IMAGE_TAG --overwrite

# TODO: Create predictive naming on task definition name
# TODO: Fix IAM user / role in tandem with this fix
    - name: Download current task definition
      run: |
        aws ecs describe-task-definition --task-definition demorasastackdemoecsrasataskdefinitionactionstestbot0600DAF2 --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: actions-testbot
        image: ${{ steps.build-image.outputs.imagetestbot }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: demo-service-actions-testbot
        cluster: demo-cluster
        wait-for-service-stability: false

    - name: Download current task definition
      run: |
        aws ecs describe-task-definition --task-definition demorasastackdemoecsrasataskdefinitionactionspalmu8358361D --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def-2
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: actions-palmu
        image: ${{ steps.build-image.outputs.imagepalmu }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-2.outputs.task-definition }}
        service: demo-service-actions-palmu
        cluster: demo-cluster
        wait-for-service-stability: false